---
title: "Code Book"
author: "Suparna Sen"
date: "25 January 2016"
output: html_document
---
This document describes the code inside run_analysis.R.

The code is divided into section by comments as per the required steps for the assignment:

1. Merges the training and the test sets to create one data set. 
2. Extracts only the measurements on the mean and standard deviation for each measurement.]
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

```
INPUT DATA : 
===========
Zip file downloaded from (data set) : 
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
```
```
OUTPUT FILE:  analysedData.txt
Requirement for the final analysed data:
========================================
Average/mean in standard units of each variable for each activity and each subject for mean and standard deviation readings ignoring the following subgroupings for the activity and the subject:

1. time and frequency domain variables
2. gravitational and body motion components
3. sensor signals (accelerometer and gyroscope)
4. 3-axial signals in the X, Y and Z directions
5. jerk signals 
6. the magnitude of three-dimensional signals

```
#### STEP 1 Reading and Merging 

```
 * READING DATA *
      - READ SUBJECT IDS
      - READ ACTIVITY IDS
      - READ activity master
      - READING features.txt has the column headers
      - READ DATA -TEST 
      - READ DATA -TRAIN
      R-Script called ** loadFiles.R **

      
* DATA CLEANING, RESHAPING AND MERGING *
    - ADDING ACTIVITY DESCRIPTION
    - CREATING SUBJECT-ACTIVITY WITH ACTIVITY DESCRIPTION INSTEAD OF CODE
    - ASSIGNING FEATURE ROWS AS COLUMN HEADER TO BOTH TEST AND TRAIN DATA
    - ADDING SUBJECT & ACTIVITY DESCRIPTION TO BOTH TEST AND TRAIN DATA
    - MERGING DATA 
    R-Script called ** reshapeCleanMerge.R **
    
```
#### STEP 2 & 3 Extracts only the measurements on the mean and standard deviation for each measurement.AND Uses descriptive activity names to name the activities in the data set

```
       R-Script called ** extractMeanStd.R **
```
#### STEP 4 Appropriately labels the data set with descriptive variable names.

```
       R-Script called ** cleanLabel.R **
```

#### STEP 5A From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
```
       R-Script called ** calculateMean.R ** 
```
```
final.df data frames after ** calculateMean.R ** execution:
===========================================================
> str(final.df)
'data.frame':	180 obs. of  68 variables:
 $ SUBJID                                     : int  1 1 1 1 1 1 10 10 10 10 ...
 $ ACTDESC                                    : chr  "LAYING" "SITTING" "STANDING" "WALKING" ...
 $ timeBodyAccelerometerMeanXaxis             : num  0.222 0.261 0.279 0.277 0.289 ...
 $ timeBodyAccelerometerMeanYaxis             : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ timeBodyAccelerometerMeanZaxis             : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ timeGravityAccelerometerMeanXaxis          : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ timeGravityAccelerometerMeanYaxis          : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ timeGravityAccelerometerMeanZaxis          : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ timeBodyAccelerometerJerkMeanXaxis         : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ timeBodyAccelerometerJerkMeanYaxis         : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ timeBodyAccelerometerJerkMeanZaxis         : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ timeBodyGyroscopeMeanXaxis                 : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ timeBodyGyroscopeMeanYaxis                 : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 ...
```
#### STEP 5B Writing final data to txt file 
```
data frame "final.df"" is written into text file named "analysedData.txt""
```
